import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowUpRight } from "lucide-react";
import { DEPARTMENTS } from "@/lib/content";
export default function Ecosystem() {
    return (_jsx("section", { className: "relative bg-background py-24 sm:py-36 grain overflow-hidden", children: _jsxs("div", { className: "max-w-[1400px] mx-auto px-5 sm:px-8", children: [_jsxs("div", { className: "text-center max-w-3xl mx-auto mb-16", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-accent mb-5", children: "Notre mission" }), _jsx("h2", { className: "font-heading text-4xl sm:text-5xl lg:text-6xl leading-[1.02] text-balance", children: "Un \u00E9cosyst\u00E8me o\u00F9 chaque acte sert l'\u00EAtre humain tout entier." })] }), _jsx("div", { className: "relative grid md:grid-cols-5 gap-0 max-w-5xl mx-auto", children: DEPARTMENTS.map((dept, i) => (_jsxs(motion.div, { initial: { opacity: 0, y: 40 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-80px" }, transition: { duration: 0.6, delay: i * 0.1 }, className: "relative", style: { marginTop: i % 2 === 1 ? "2.5rem" : 0 }, children: [_jsx("div", { className: "mx-auto w-px h-16 bg-accent/40", style: { marginLeft: "50%", transform: "translateX(-50%)" } }), _jsxs("div", { className: "text-center px-3", children: [_jsxs("span", { className: "inline-flex items-center justify-center w-12 h-12 rounded-full border border-accent/40 text-accent text-sm font-heading mb-3", children: ["0", i + 1] }), _jsx("p", { className: "font-heading text-lg leading-tight", children: dept.name }), _jsx("p", { className: "text-xs text-foreground/50 mt-1.5 leading-snug hidden sm:block", children: dept.tagline })] })] }, dept.slug))) }), _jsxs("div", { className: "relative max-w-5xl mx-auto mt-8", children: [_jsx("div", { className: "horizon-line h-px w-full" }), _jsx("div", { className: "text-center mt-8", children: _jsx("p", { className: "font-heading italic text-lg sm:text-xl text-foreground/70 max-w-2xl mx-auto text-balance", children: "\u00AB L'\u00C9vangile n'est pas une parole qu'on \u00E9coute \u2014 c'est une vie qu'on transmet. \u00BB" }) })] }), _jsx("div", { className: "text-center mt-12", children: _jsxs(Link, { to: "/mission", className: "inline-flex items-center gap-2 text-sm font-medium text-accent hover:gap-3 transition-all", children: ["Lire notre histoire compl\u00E8te ", _jsx(ArrowUpRight, { size: 16 })] }) })] }) }));
}
