import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowUpRight, CalendarDays, MapPin } from "lucide-react";
import { NEWS, EVENTS } from "@/lib/content";
export default function NewsEvents() {
    return (_jsx("section", { className: "bg-background py-24 sm:py-36", children: _jsx("div", { className: "max-w-[1400px] mx-auto px-5 sm:px-8", children: _jsxs("div", { className: "grid lg:grid-cols-12 gap-16", children: [_jsxs("div", { className: "lg:col-span-7", children: [_jsxs("div", { className: "flex items-end justify-between mb-10", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-accent mb-3", children: "Actualit\u00E9s" }), _jsx("h2", { className: "font-heading text-3xl sm:text-4xl", children: "Les derni\u00E8res nouvelles" })] }), _jsx(Link, { to: "/actualites", className: "text-sm text-accent hover:underline shrink-0", children: "Tout voir" })] }), _jsx("div", { className: "space-y-px bg-border", children: NEWS.map((item, i) => (_jsxs(motion.article, { initial: { opacity: 0, y: 15 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-60px" }, transition: { duration: 0.5, delay: i * 0.08 }, className: "bg-background p-7 group cursor-pointer hover:bg-secondary/40 transition-colors", children: [_jsxs("div", { className: "flex items-center gap-4 mb-3", children: [_jsx("span", { className: "text-[10px] uppercase tracking-[0.2em] text-accent border border-accent/30 px-2.5 py-1", children: item.tag }), _jsx("span", { className: "text-xs text-foreground/40", children: item.date })] }), _jsx("h3", { className: "font-heading text-xl sm:text-2xl leading-snug mb-2 group-hover:text-accent transition-colors", children: item.title }), _jsx("p", { className: "text-foreground/60 text-sm leading-relaxed", children: item.excerpt })] }, i))) })] }), _jsxs("div", { className: "lg:col-span-5", children: [_jsxs("div", { className: "mb-10", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-accent mb-3", children: "\u00C9v\u00E9nements" }), _jsx("h2", { className: "font-heading text-3xl sm:text-4xl", children: "\u00C0 venir" })] }), _jsx("div", { className: "space-y-5", children: EVENTS.map((ev, i) => {
                                    const d = new Date(ev.date);
                                    const day = d.toLocaleDateString("fr-FR", { day: "2-digit" });
                                    const month = d.toLocaleDateString("fr-FR", { month: "short" });
                                    return (_jsxs(motion.div, { initial: { opacity: 0, y: 15 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-60px" }, transition: { duration: 0.5, delay: i * 0.08 }, className: "flex items-center gap-5 p-5 border border-border hover:border-accent/50 transition-colors group", children: [_jsxs("div", { className: "text-center shrink-0 w-14", children: [_jsx("p", { className: "font-heading text-3xl text-accent leading-none", children: day }), _jsx("p", { className: "text-xs uppercase tracking-wide text-foreground/50 mt-1", children: month })] }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h3", { className: "font-medium leading-snug group-hover:text-accent transition-colors", children: ev.title }), _jsxs("p", { className: "flex items-center gap-1.5 text-xs text-foreground/50 mt-1.5", children: [_jsx(MapPin, { size: 12 }), " ", ev.location] })] }), _jsx(CalendarDays, { size: 18, className: "text-foreground/30 group-hover:text-accent transition-colors shrink-0" })] }, i));
                                }) }), _jsxs(Link, { to: "/actualites", className: "mt-8 inline-flex items-center gap-2 text-sm text-accent hover:gap-3 transition-all", children: ["Voir le calendrier complet ", _jsx(ArrowUpRight, { size: 15 })] })] })] }) }) }));
}
