import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Quote, ChevronLeft, ChevronRight } from "lucide-react";
import { TESTIMONIALS } from "@/lib/content";
export default function Testimonials() {
    const [idx, setIdx] = useState(0);
    const t = TESTIMONIALS[idx];
    const go = (dir) => setIdx((p) => (p + dir + TESTIMONIALS.length) % TESTIMONIALS.length);
    return (_jsx("section", { id: "temoignages", className: "relative bg-primary text-primary-foreground py-24 sm:py-36 overflow-hidden pottery-pattern", children: _jsxs("div", { className: "max-w-[1100px] mx-auto px-5 sm:px-8 text-center", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-accent mb-5", children: "T\u00E9moignages" }), _jsx("h2", { className: "font-heading text-3xl sm:text-4xl lg:text-5xl mb-16 text-balance", children: "Des vies transform\u00E9es, des histoires de dignit\u00E9 retrouv\u00E9e." }), _jsxs("div", { className: "relative min-h-[280px] sm:min-h-[240px]", children: [_jsx(Quote, { className: "mx-auto text-accent/40 mb-8", size: 40 }), _jsx(AnimatePresence, { mode: "wait", children: _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -20 }, transition: { duration: 0.5 }, children: [_jsxs("p", { className: "font-heading text-2xl sm:text-3xl lg:text-4xl leading-snug text-balance text-primary-foreground/95", children: ["\u00AB ", t.quote, " \u00BB"] }), _jsx("p", { className: "mt-8 font-medium text-accent", children: t.name }), _jsx("p", { className: "text-sm text-primary-foreground/50", children: t.role })] }, idx) })] }), _jsxs("div", { className: "flex items-center justify-center gap-6 mt-12", children: [_jsx("button", { onClick: () => go(-1), className: "p-2 border border-white/15 hover:border-accent hover:text-accent transition-colors", "aria-label": "Pr\u00E9c\u00E9dent", children: _jsx(ChevronLeft, { size: 18 }) }), _jsx("div", { className: "flex gap-2", children: TESTIMONIALS.map((_, i) => (_jsx("button", { onClick: () => setIdx(i), className: `h-1.5 transition-all ${i === idx ? "w-8 bg-accent" : "w-1.5 bg-white/25"}`, "aria-label": `Témoignage ${i + 1}` }, i))) }), _jsx("button", { onClick: () => go(1), className: "p-2 border border-white/15 hover:border-accent hover:text-accent transition-colors", "aria-label": "Suivant", children: _jsx(ChevronRight, { size: 18 }) })] })] }) }));
}
